In [26]:
#HOTEL
#Import
import pandas as pd
import numpy as np

In [27]:
# Read the Excel file into a pandas DataFrame
filedata = r"C:\Users\umay2\Desktop\SUFFER\UNIV\SEMESTER 2\Basis Data\PRAKTIKUM BASDAT\Tugas 1\Hotel\hotel_excelvr_0nf.xlsx"
readexcel = pd.read_excel(filedata)
df= pd.DataFrame(readexcel)
print("DATA INVENTORY")
print(df)

DATA INVENTORY
   Booking_ID Guest_ID  adults  children  weekend nights  week nights  \
0    INN00001  GI00001       1         1               2            5
1    INN00002  GI00002       1         0               1            3
2    INN00003  GI00003       2         1               1            3
3    INN00004  GI00004       1         0               0            2
4    INN00005  GI00005       1         0               1            2
5    INN00006  GI00006       1         0               0            2
6    INN00007  GI00007       1         1               1            4
7    INN00008  GI00008       3         0               1            3
8    INN00009  GI00009       1         1               0            4
9    INN00010  GI00010       2         0               0            5
10   INN00011  GI00011       1         0               1            0
11   INN00012  GI00012       1         0               2            1
12   INN00013  GI00013       2         0               2            1
13   INN00014  GI00014       1         0               2            0
14   INN00015  GI00015       2         0               0            2
15   INN00016  GI00016       2         0               0            2
16   INN00017  GI00017       1         0               1            0
17   INN00018  GI00018       2         0               1            3
18   INN00019  GI00019       2         0               2            2
19   INN00020  GI00020       2         0               1            0
20   INN00021  GI00021       2         0               2            2
21   INN00022  GI00022       1         0               0            1
22   INN00023  GI00023       2         0               2            4
23   INN00024  GI00024       2         0               0            3
24   INN00025  GI00025       2         0               2            1
25   INN00026  GI00026       2         0               0            2
26   INN00027  GI00027       2         0               1            1
27   INN00028  GI00028       1         0               0            2
28   INN00029  GI00029       1         0               1            2
29   INN00030  GI00030       2         0               0            2
30   INN00031  GI00031       2         0               1            1
31   INN00032  GI00032       2         0               2            2
32   INN00033  GI00033       0         2               0            3
33   INN00034  GI00034       2         0               0            1
34   INN00035  GI00035       2         0               0            2
35   INN00036  GI00036       2         0               0            1
36   INN00037  GI00037       1         0               2            1
37   INN00038  GI00038       2         0               0            1
38   INN00039  GI00039       2         0               2            3
39   INN00040  GI00040       2         0               2            1
40   INN00041  GI00041       2         0               0            4
41   INN00042  GI00042       2         0               0            2
42   INN00043  GI00043       3         0               2            1
43   INN00044  GI00044       2         0               1            1
44   INN00045  GI00045       2         0               0            4
45   INN00046  GI00046       2         0               0            3
46   INN00047  GI00047       1         0               0            2
47   INN00048  GI00048       2         0               0            1
48   INN00049  GI00049       2         0               0            4

           meal  parking    room type  lead time     source   price  requests  \
0   Meal Plan 1        0  Room_Type 1        224    Offline   88.00         0
1           NaN        0  Room_Type 1          5     Online  106.68         1
2   Meal Plan 1        0  Room_Type 2          1     Online   50.00         0
3   Meal Plan 1        0          NaN        211     Online  100.00         1
4           NaN        0  Room_Type 1         48     Online   77.00         0
5   Meal Plan 2        0  Room_Type 1        346    Offline  100.00         1
6   Meal Plan 1        0  Room_Type 1         34     Online  107.55         1
7   Meal Plan 2        0  Room_Type 4         83     Online  105.61         1
8   Meal Plan 1        0          NaN        121    Offline   96.90         1
9   Meal Plan 1        0  Room_Type 4         44     Online  133.44         3
10          NaN        0  Room_Type 1          0     Online   85.03         0
11  Meal Plan 1        0  Room_Type 4         35     Online  140.40         1
12          NaN        0  Room_Type 1         30     Online   88.00         0
13  Meal Plan 1        0  Room_Type 1         95     Online   90.00         2
14  Meal Plan 1        0  Room_Type 1         47     Online   94.50         2
15  Meal Plan 2        0  Room_Type 2        256     Online  115.00         1
16  Meal Plan 1        0          NaN          0    Offline   96.00         0
17          NaN        0  Room_Type 1          1     Online   96.00         1
18  Meal Plan 1        0  Room_Type 2         99     Online   65.00         0
19  Meal Plan 1        0  Room_Type 1         12    Offline   72.00         0
20  Meal Plan 2        0  Room_Type 1         99     Online   65.00         0
21  Meal Plan 1        0  Room_Type 1        122  Corporate   67.00         0
22  Meal Plan 2        0          NaN          2    Offline   85.00         0
23  Meal Plan 1        0          NaN         37    Offline  105.00         0
24          NaN        0  Room_Type 1        130     Online   94.50         1
25  Meal Plan 1        0  Room_Type 1         99     Online  114.30         1
26  Meal Plan 2        0  Room_Type 1         60    Offline   65.00         0
27  Meal Plan 1        0  Room_Type 4          2   Aviation  110.00         0
28  Meal Plan 2        0  Room_Type 1         37     Online   37.33         0
29  Meal Plan 2        0  Room_Type 1         56    Offline   82.00         0
30  Meal Plan 1        0          NaN          3     Online  177.50         1
31  Meal Plan 1        0  Room_Type 1        107     Online   87.50         1
32  Meal Plan 1        0  Room_Type 2         56     Online   82.44         1
33          NaN        0  Room_Type 1          2     Online   69.50         1
34  Meal Plan 1        0  Room_Type 2         72    Offline   85.50         0
35          NaN        1          NaN         23     Online  115.00         1
36  Meal Plan 1        0  Room_Type 1         34     Online   81.00         0
37  Meal Plan 1        0  Room_Type 1        289    Offline   67.00         0
38          NaN        0  Room_Type 1        247     Online   63.75         0
39  Meal Plan 1        0  Room_Type 4        186     Online  121.80         1
40  Meal Plan 2        0  Room_Type 1         64     Online   93.60         2
41  Meal Plan 1        0          NaN         35     Online  102.00         1
42  Meal Plan 1        0  Room_Type 1         96     Online  121.80         1
43          NaN        0  Room_Type 2         41     Online   98.10         1
44  Meal Plan 1        0  Room_Type 4         55    Offline   60.00         1
45  Meal Plan 1        0  Room_Type 1        146    Offline   75.00         0
46  Meal Plan 1        0          NaN         32    Offline   73.00         0
47  Meal Plan 2        0  Room_Type 1         55    Offline  104.00         0
48          NaN        0  Room_Type 1         57     Online   79.20         1

    date of reservation booking status
0   2015-02-10 00:00:00   Not_Canceled
1   2018-06-11 00:00:00   Not_Canceled
2             2/28/2018       Canceled
3             5/20/2017       Canceled
4   2018-11-04 00:00:00       Canceled
5             9/13/2016       Canceled
6            10/15/2017   Not_Canceled
7            12/26/2018   Not_Canceled
8   2018-06-07 00:00:00   Not_Canceled
9            10/18/2018   Not_Canceled
10  2018-11-09 00:00:00   Not_Canceled
11            4/30/2018   Not_Canceled
12           11/26/2018       Canceled
13           11/20/2018       Canceled
14           10/20/2017   Not_Canceled
15            6/15/2018       Canceled
16  2017-05-10 00:00:00   Not_Canceled
17  2017-10-08 00:00:00   Not_Canceled
18           10/30/2017       Canceled
19  2017-04-10 00:00:00   Not_Canceled
20           10/30/2017       Canceled
21           11/25/2018   Not_Canceled
22            3/20/2018   Not_Canceled
23           10/13/2018   Not_Canceled
24            5/22/2018   Not_Canceled
25            4/28/2018   Not_Canceled
26            9/21/2017   Not_Canceled
27            5/19/2018       Canceled
28  2017-06-11 00:00:00       Canceled
29            9/17/2017   Not_Canceled
30            9/19/2017   Not_Canceled
31           11/13/2018   Not_Canceled
32  2018-07-12 00:00:00   Not_Canceled
33  2018-09-01 00:00:00   Not_Canceled
34  2018-07-10 00:00:00   Not_Canceled
35            4/27/2018   Not_Canceled
36            6/19/2018       Canceled
37           10/17/2017   Not_Canceled
38           11/19/2018       Canceled
39            7/30/2018       Canceled
40  2018-01-11 00:00:00   Not_Canceled
41            6/21/2018   Not_Canceled
42  2018-10-04 00:00:00   Not_Canceled
43            6/27/2018       Canceled
44           11/18/2017   Not_Canceled
45           12/29/2017   Not_Canceled
46           11/20/2017   Not_Canceled
47  2018-06-04 00:00:00   Not_Canceled
48  2018-01-11 00:00:00   Not_Canceled

In [28]:
#1NF
#Cek bila ada data yang kosong
onenf= pd.isnull(df).sum()
print(onenf)

Booking_ID              0
Guest_ID                0
adults                  0
children                0
weekend nights          0
week nights             0
meal                   11
parking                 0
room type               9
lead time               0
source                  0
price                   0
requests                0
date of reservation     0
booking status          0
dtype: int64

In [29]:
#Isi kolum meal dengan Meal Plan 1
for i in range(len(df['meal'])):
    if pd.isnull(df.loc[i, 'meal'])==True:
        df.loc[i,'meal']="Meal Plan 1"
#Isi kolum room type dengan Room_Type 1
for i in range(len(df['room type'])):
    if pd.isnull(df.loc[i, 'room type'])==True:
        df.loc[i,'room type']="Room_Type 1"
#transfer hasil 1NF
df.to_excel("C:\\Users\\umay2\\Desktop\\SUFFER\\UNIV\\SEMESTER 2\\Basis Data\\PRAKTIKUM BASDAT\\Tugas 1\\Hotel\\hotel_excelvr_1nf.xlsx")

In [30]:
#2NF
#Hilagkan partial dependency 
#membuat 2 kelompok kolum terdiri dari detail guest dan booking details
guestid = df[['Booking_ID','Guest_ID', 'adults', 'children','meal','parking','requests']]
bookingid= df[['Booking_ID','weekend nights', 'week nights','room type','lead time',
               'price','date of reservation','booking status']]
#hasil 2nf
print("GUESTS DETAILS")
print(bookingid)
print("BOOKING DETAILS")
print(guestid)
#transfer hasil 2nf
with pd.ExcelWriter("C:\\Users\\umay2\\Desktop\\SUFFER\\UNIV\\SEMESTER 2\\Basis Data\\PRAKTIKUM BASDAT\\Tugas 1\\Hotel\\hotel_excelvr_2nf.xlsx") as writer:
    bookingid.to_excel(writer, sheet_name="GUESTS DETAILS")
    guestid.to_excel(writer, sheet_name="BOOKING DETAILS")

GUESTS DETAILS
   Booking_ID  weekend nights  week nights    room type  lead time   price  \
0    INN00001               2            5  Room_Type 1        224   88.00
1    INN00002               1            3  Room_Type 1          5  106.68
2    INN00003               1            3  Room_Type 2          1   50.00
3    INN00004               0            2  Room_Type 1        211  100.00
4    INN00005               1            2  Room_Type 1         48   77.00
5    INN00006               0            2  Room_Type 1        346  100.00
6    INN00007               1            4  Room_Type 1         34  107.55
7    INN00008               1            3  Room_Type 4         83  105.61
8    INN00009               0            4  Room_Type 1        121   96.90
9    INN00010               0            5  Room_Type 4         44  133.44
10   INN00011               1            0  Room_Type 1          0   85.03
11   INN00012               2            1  Room_Type 4         35  140.40
12   INN00013               2            1  Room_Type 1         30   88.00
13   INN00014               2            0  Room_Type 1         95   90.00
14   INN00015               0            2  Room_Type 1         47   94.50
15   INN00016               0            2  Room_Type 2        256  115.00
16   INN00017               1            0  Room_Type 1          0   96.00
17   INN00018               1            3  Room_Type 1          1   96.00
18   INN00019               2            2  Room_Type 2         99   65.00
19   INN00020               1            0  Room_Type 1         12   72.00
20   INN00021               2            2  Room_Type 1         99   65.00
21   INN00022               0            1  Room_Type 1        122   67.00
22   INN00023               2            4  Room_Type 1          2   85.00
23   INN00024               0            3  Room_Type 1         37  105.00
24   INN00025               2            1  Room_Type 1        130   94.50
25   INN00026               0            2  Room_Type 1         99  114.30
26   INN00027               1            1  Room_Type 1         60   65.00
27   INN00028               0            2  Room_Type 4          2  110.00
28   INN00029               1            2  Room_Type 1         37   37.33
29   INN00030               0            2  Room_Type 1         56   82.00
30   INN00031               1            1  Room_Type 1          3  177.50
31   INN00032               2            2  Room_Type 1        107   87.50
32   INN00033               0            3  Room_Type 2         56   82.44
33   INN00034               0            1  Room_Type 1          2   69.50
34   INN00035               0            2  Room_Type 2         72   85.50
35   INN00036               0            1  Room_Type 1         23  115.00
36   INN00037               2            1  Room_Type 1         34   81.00
37   INN00038               0            1  Room_Type 1        289   67.00
38   INN00039               2            3  Room_Type 1        247   63.75
39   INN00040               2            1  Room_Type 4        186  121.80
40   INN00041               0            4  Room_Type 1         64   93.60
41   INN00042               0            2  Room_Type 1         35  102.00
42   INN00043               2            1  Room_Type 1         96  121.80
43   INN00044               1            1  Room_Type 2         41   98.10
44   INN00045               0            4  Room_Type 4         55   60.00
45   INN00046               0            3  Room_Type 1        146   75.00
46   INN00047               0            2  Room_Type 1         32   73.00
47   INN00048               0            1  Room_Type 1         55  104.00
48   INN00049               0            4  Room_Type 1         57   79.20

    date of reservation booking status
0   2015-02-10 00:00:00   Not_Canceled
1   2018-06-11 00:00:00   Not_Canceled
2             2/28/2018       Canceled
3             5/20/2017       Canceled
4   2018-11-04 00:00:00       Canceled
5             9/13/2016       Canceled
6            10/15/2017   Not_Canceled
7            12/26/2018   Not_Canceled
8   2018-06-07 00:00:00   Not_Canceled
9            10/18/2018   Not_Canceled
10  2018-11-09 00:00:00   Not_Canceled
11            4/30/2018   Not_Canceled
12           11/26/2018       Canceled
13           11/20/2018       Canceled
14           10/20/2017   Not_Canceled
15            6/15/2018       Canceled
16  2017-05-10 00:00:00   Not_Canceled
17  2017-10-08 00:00:00   Not_Canceled
18           10/30/2017       Canceled
19  2017-04-10 00:00:00   Not_Canceled
20           10/30/2017       Canceled
21           11/25/2018   Not_Canceled
22            3/20/2018   Not_Canceled
23           10/13/2018   Not_Canceled
24            5/22/2018   Not_Canceled
25            4/28/2018   Not_Canceled
26            9/21/2017   Not_Canceled
27            5/19/2018       Canceled
28  2017-06-11 00:00:00       Canceled
29            9/17/2017   Not_Canceled
30            9/19/2017   Not_Canceled
31           11/13/2018   Not_Canceled
32  2018-07-12 00:00:00   Not_Canceled
33  2018-09-01 00:00:00   Not_Canceled
34  2018-07-10 00:00:00   Not_Canceled
35            4/27/2018   Not_Canceled
36            6/19/2018       Canceled
37           10/17/2017   Not_Canceled
38           11/19/2018       Canceled
39            7/30/2018       Canceled
40  2018-01-11 00:00:00   Not_Canceled
41            6/21/2018   Not_Canceled
42  2018-10-04 00:00:00   Not_Canceled
43            6/27/2018       Canceled
44           11/18/2017   Not_Canceled
45           12/29/2017   Not_Canceled
46           11/20/2017   Not_Canceled
47  2018-06-04 00:00:00   Not_Canceled
48  2018-01-11 00:00:00   Not_Canceled
BOOKING DETAILS
   Booking_ID Guest_ID  adults  children         meal  parking  requests
0    INN00001  GI00001       1         1  Meal Plan 1        0         0
1    INN00002  GI00002       1         0  Meal Plan 1        0         1
2    INN00003  GI00003       2         1  Meal Plan 1        0         0
3    INN00004  GI00004       1         0  Meal Plan 1        0         1
4    INN00005  GI00005       1         0  Meal Plan 1        0         0
5    INN00006  GI00006       1         0  Meal Plan 2        0         1
6    INN00007  GI00007       1         1  Meal Plan 1        0         1
7    INN00008  GI00008       3         0  Meal Plan 2        0         1
8    INN00009  GI00009       1         1  Meal Plan 1        0         1
9    INN00010  GI00010       2         0  Meal Plan 1        0         3
10   INN00011  GI00011       1         0  Meal Plan 1        0         0
11   INN00012  GI00012       1         0  Meal Plan 1        0         1
12   INN00013  GI00013       2         0  Meal Plan 1        0         0
13   INN00014  GI00014       1         0  Meal Plan 1        0         2
14   INN00015  GI00015       2         0  Meal Plan 1        0         2
15   INN00016  GI00016       2         0  Meal Plan 2        0         1
16   INN00017  GI00017       1         0  Meal Plan 1        0         0
17   INN00018  GI00018       2         0  Meal Plan 1        0         1
18   INN00019  GI00019       2         0  Meal Plan 1        0         0
19   INN00020  GI00020       2         0  Meal Plan 1        0         0
20   INN00021  GI00021       2         0  Meal Plan 2        0         0
21   INN00022  GI00022       1         0  Meal Plan 1        0         0
22   INN00023  GI00023       2         0  Meal Plan 2        0         0
23   INN00024  GI00024       2         0  Meal Plan 1        0         0
24   INN00025  GI00025       2         0  Meal Plan 1        0         1
25   INN00026  GI00026       2         0  Meal Plan 1        0         1
26   INN00027  GI00027       2         0  Meal Plan 2        0         0
27   INN00028  GI00028       1         0  Meal Plan 1        0         0
28   INN00029  GI00029       1         0  Meal Plan 2        0         0
29   INN00030  GI00030       2         0  Meal Plan 2        0         0
30   INN00031  GI00031       2         0  Meal Plan 1        0         1
31   INN00032  GI00032       2         0  Meal Plan 1        0         1
32   INN00033  GI00033       0         2  Meal Plan 1        0         1
33   INN00034  GI00034       2         0  Meal Plan 1        0         1
34   INN00035  GI00035       2         0  Meal Plan 1        0         0
35   INN00036  GI00036       2         0  Meal Plan 1        1         1
36   INN00037  GI00037       1         0  Meal Plan 1        0         0
37   INN00038  GI00038       2         0  Meal Plan 1        0         0
38   INN00039  GI00039       2         0  Meal Plan 1        0         0
39   INN00040  GI00040       2         0  Meal Plan 1        0         1
40   INN00041  GI00041       2         0  Meal Plan 2        0         2
41   INN00042  GI00042       2         0  Meal Plan 1        0         1
42   INN00043  GI00043       3         0  Meal Plan 1        0         1
43   INN00044  GI00044       2         0  Meal Plan 1        0         1
44   INN00045  GI00045       2         0  Meal Plan 1        0         1
45   INN00046  GI00046       2         0  Meal Plan 1        0         0
46   INN00047  GI00047       1         0  Meal Plan 1        0         0
47   INN00048  GI00048       2         0  Meal Plan 2        0         0
48   INN00049  GI00049       2         0  Meal Plan 1        0         1

In [31]:
#3NF
#Hilagkan transitive dependency 
#membuat 3 kelompok kolum
status = df[['Guest_ID','Booking_ID', 'booking status']]
guestid = df[['Guest_ID','Booking_ID', 'adults', 'children','meal','parking','requests']]
bookingid= df[['Booking_ID','weekend nights', 'week nights','room type','lead time',
               'price','date of reservation','booking status']]
#hasil 3nf
print("STATUS")
print(status)
print("GUESTS DETAILS")
print(bookingid)
print("BOOKING DETAILS")
print(guestid)
#transfer hasil 3nf
with pd.ExcelWriter("C:\\Users\\umay2\\Desktop\\SUFFER\\UNIV\\SEMESTER 2\\Basis Data\\PRAKTIKUM BASDAT\\Tugas 1\\Hotel\\hotel_excelvr_3nf.xlsx") as writer:
    status.to_excel(writer, sheet_name="STATUS")
    bookingid.to_excel(writer, sheet_name="BOOKING DETAILS")
    guestid.to_excel(writer, sheet_name="GUEST DETAILS")

STATUS
   Guest_ID Booking_ID booking status
0   GI00001   INN00001   Not_Canceled
1   GI00002   INN00002   Not_Canceled
2   GI00003   INN00003       Canceled
3   GI00004   INN00004       Canceled
4   GI00005   INN00005       Canceled
5   GI00006   INN00006       Canceled
6   GI00007   INN00007   Not_Canceled
7   GI00008   INN00008   Not_Canceled
8   GI00009   INN00009   Not_Canceled
9   GI00010   INN00010   Not_Canceled
10  GI00011   INN00011   Not_Canceled
11  GI00012   INN00012   Not_Canceled
12  GI00013   INN00013       Canceled
13  GI00014   INN00014       Canceled
14  GI00015   INN00015   Not_Canceled
15  GI00016   INN00016       Canceled
16  GI00017   INN00017   Not_Canceled
17  GI00018   INN00018   Not_Canceled
18  GI00019   INN00019       Canceled
19  GI00020   INN00020   Not_Canceled
20  GI00021   INN00021       Canceled
21  GI00022   INN00022   Not_Canceled
22  GI00023   INN00023   Not_Canceled
23  GI00024   INN00024   Not_Canceled
24  GI00025   INN00025   Not_Canceled
25  GI00026   INN00026   Not_Canceled
26  GI00027   INN00027   Not_Canceled
27  GI00028   INN00028       Canceled
28  GI00029   INN00029       Canceled
29  GI00030   INN00030   Not_Canceled
30  GI00031   INN00031   Not_Canceled
31  GI00032   INN00032   Not_Canceled
32  GI00033   INN00033   Not_Canceled
33  GI00034   INN00034   Not_Canceled
34  GI00035   INN00035   Not_Canceled
35  GI00036   INN00036   Not_Canceled
36  GI00037   INN00037       Canceled
37  GI00038   INN00038   Not_Canceled
38  GI00039   INN00039       Canceled
39  GI00040   INN00040       Canceled
40  GI00041   INN00041   Not_Canceled
41  GI00042   INN00042   Not_Canceled
42  GI00043   INN00043   Not_Canceled
43  GI00044   INN00044       Canceled
44  GI00045   INN00045   Not_Canceled
45  GI00046   INN00046   Not_Canceled
46  GI00047   INN00047   Not_Canceled
47  GI00048   INN00048   Not_Canceled
48  GI00049   INN00049   Not_Canceled
GUESTS DETAILS
   Booking_ID  weekend nights  week nights    room type  lead time   price  \
0    INN00001               2            5  Room_Type 1        224   88.00
1    INN00002               1            3  Room_Type 1          5  106.68
2    INN00003               1            3  Room_Type 2          1   50.00
3    INN00004               0            2  Room_Type 1        211  100.00
4    INN00005               1            2  Room_Type 1         48   77.00
5    INN00006               0            2  Room_Type 1        346  100.00
6    INN00007               1            4  Room_Type 1         34  107.55
7    INN00008               1            3  Room_Type 4         83  105.61
8    INN00009               0            4  Room_Type 1        121   96.90
9    INN00010               0            5  Room_Type 4         44  133.44
10   INN00011               1            0  Room_Type 1          0   85.03
11   INN00012               2            1  Room_Type 4         35  140.40
12   INN00013               2            1  Room_Type 1         30   88.00
13   INN00014               2            0  Room_Type 1         95   90.00
14   INN00015               0            2  Room_Type 1         47   94.50
15   INN00016               0            2  Room_Type 2        256  115.00
16   INN00017               1            0  Room_Type 1          0   96.00
17   INN00018               1            3  Room_Type 1          1   96.00
18   INN00019               2            2  Room_Type 2         99   65.00
19   INN00020               1            0  Room_Type 1         12   72.00
20   INN00021               2            2  Room_Type 1         99   65.00
21   INN00022               0            1  Room_Type 1        122   67.00
22   INN00023               2            4  Room_Type 1          2   85.00
23   INN00024               0            3  Room_Type 1         37  105.00
24   INN00025               2            1  Room_Type 1        130   94.50
25   INN00026               0            2  Room_Type 1         99  114.30
26   INN00027               1            1  Room_Type 1         60   65.00
27   INN00028               0            2  Room_Type 4          2  110.00
28   INN00029               1            2  Room_Type 1         37   37.33
29   INN00030               0            2  Room_Type 1         56   82.00
30   INN00031               1            1  Room_Type 1          3  177.50
31   INN00032               2            2  Room_Type 1        107   87.50
32   INN00033               0            3  Room_Type 2         56   82.44
33   INN00034               0            1  Room_Type 1          2   69.50
34   INN00035               0            2  Room_Type 2         72   85.50
35   INN00036               0            1  Room_Type 1         23  115.00
36   INN00037               2            1  Room_Type 1         34   81.00
37   INN00038               0            1  Room_Type 1        289   67.00
38   INN00039               2            3  Room_Type 1        247   63.75
39   INN00040               2            1  Room_Type 4        186  121.80
40   INN00041               0            4  Room_Type 1         64   93.60
41   INN00042               0            2  Room_Type 1         35  102.00
42   INN00043               2            1  Room_Type 1         96  121.80
43   INN00044               1            1  Room_Type 2         41   98.10
44   INN00045               0            4  Room_Type 4         55   60.00
45   INN00046               0            3  Room_Type 1        146   75.00
46   INN00047               0            2  Room_Type 1         32   73.00
47   INN00048               0            1  Room_Type 1         55  104.00
48   INN00049               0            4  Room_Type 1         57   79.20

    date of reservation booking status
0   2015-02-10 00:00:00   Not_Canceled
1   2018-06-11 00:00:00   Not_Canceled
2             2/28/2018       Canceled
3             5/20/2017       Canceled
4   2018-11-04 00:00:00       Canceled
5             9/13/2016       Canceled
6            10/15/2017   Not_Canceled
7            12/26/2018   Not_Canceled
8   2018-06-07 00:00:00   Not_Canceled
9            10/18/2018   Not_Canceled
10  2018-11-09 00:00:00   Not_Canceled
11            4/30/2018   Not_Canceled
12           11/26/2018       Canceled
13           11/20/2018       Canceled
14           10/20/2017   Not_Canceled
15            6/15/2018       Canceled
16  2017-05-10 00:00:00   Not_Canceled
17  2017-10-08 00:00:00   Not_Canceled
18           10/30/2017       Canceled
19  2017-04-10 00:00:00   Not_Canceled
20           10/30/2017       Canceled
21           11/25/2018   Not_Canceled
22            3/20/2018   Not_Canceled
23           10/13/2018   Not_Canceled
24            5/22/2018   Not_Canceled
25            4/28/2018   Not_Canceled
26            9/21/2017   Not_Canceled
27            5/19/2018       Canceled
28  2017-06-11 00:00:00       Canceled
29            9/17/2017   Not_Canceled
30            9/19/2017   Not_Canceled
31           11/13/2018   Not_Canceled
32  2018-07-12 00:00:00   Not_Canceled
33  2018-09-01 00:00:00   Not_Canceled
34  2018-07-10 00:00:00   Not_Canceled
35            4/27/2018   Not_Canceled
36            6/19/2018       Canceled
37           10/17/2017   Not_Canceled
38           11/19/2018       Canceled
39            7/30/2018       Canceled
40  2018-01-11 00:00:00   Not_Canceled
41            6/21/2018   Not_Canceled
42  2018-10-04 00:00:00   Not_Canceled
43            6/27/2018       Canceled
44           11/18/2017   Not_Canceled
45           12/29/2017   Not_Canceled
46           11/20/2017   Not_Canceled
47  2018-06-04 00:00:00   Not_Canceled
48  2018-01-11 00:00:00   Not_Canceled
BOOKING DETAILS
   Guest_ID Booking_ID  adults  children         meal  parking  requests
0   GI00001   INN00001       1         1  Meal Plan 1        0         0
1   GI00002   INN00002       1         0  Meal Plan 1        0         1
2   GI00003   INN00003       2         1  Meal Plan 1        0         0
3   GI00004   INN00004       1         0  Meal Plan 1        0         1
4   GI00005   INN00005       1         0  Meal Plan 1        0         0
5   GI00006   INN00006       1         0  Meal Plan 2        0         1
6   GI00007   INN00007       1         1  Meal Plan 1        0         1
7   GI00008   INN00008       3         0  Meal Plan 2        0         1
8   GI00009   INN00009       1         1  Meal Plan 1        0         1
9   GI00010   INN00010       2         0  Meal Plan 1        0         3
10  GI00011   INN00011       1         0  Meal Plan 1        0         0
11  GI00012   INN00012       1         0  Meal Plan 1        0         1
12  GI00013   INN00013       2         0  Meal Plan 1        0         0
13  GI00014   INN00014       1         0  Meal Plan 1        0         2
14  GI00015   INN00015       2         0  Meal Plan 1        0         2
15  GI00016   INN00016       2         0  Meal Plan 2        0         1
16  GI00017   INN00017       1         0  Meal Plan 1        0         0
17  GI00018   INN00018       2         0  Meal Plan 1        0         1
18  GI00019   INN00019       2         0  Meal Plan 1        0         0
19  GI00020   INN00020       2         0  Meal Plan 1        0         0
20  GI00021   INN00021       2         0  Meal Plan 2        0         0
21  GI00022   INN00022       1         0  Meal Plan 1        0         0
22  GI00023   INN00023       2         0  Meal Plan 2        0         0
23  GI00024   INN00024       2         0  Meal Plan 1        0         0
24  GI00025   INN00025       2         0  Meal Plan 1        0         1
25  GI00026   INN00026       2         0  Meal Plan 1        0         1
26  GI00027   INN00027       2         0  Meal Plan 2        0         0
27  GI00028   INN00028       1         0  Meal Plan 1        0         0
28  GI00029   INN00029       1         0  Meal Plan 2        0         0
29  GI00030   INN00030       2         0  Meal Plan 2        0         0
30  GI00031   INN00031       2         0  Meal Plan 1        0         1
31  GI00032   INN00032       2         0  Meal Plan 1        0         1
32  GI00033   INN00033       0         2  Meal Plan 1        0         1
33  GI00034   INN00034       2         0  Meal Plan 1        0         1
34  GI00035   INN00035       2         0  Meal Plan 1        0         0
35  GI00036   INN00036       2         0  Meal Plan 1        1         1
36  GI00037   INN00037       1         0  Meal Plan 1        0         0
37  GI00038   INN00038       2         0  Meal Plan 1        0         0
38  GI00039   INN00039       2         0  Meal Plan 1        0         0
39  GI00040   INN00040       2         0  Meal Plan 1        0         1
40  GI00041   INN00041       2         0  Meal Plan 2        0         2
41  GI00042   INN00042       2         0  Meal Plan 1        0         1
42  GI00043   INN00043       3         0  Meal Plan 1        0         1
43  GI00044   INN00044       2         0  Meal Plan 1        0         1
44  GI00045   INN00045       2         0  Meal Plan 1        0         1
45  GI00046   INN00046       2         0  Meal Plan 1        0         0
46  GI00047   INN00047       1         0  Meal Plan 1        0         0
47  GI00048   INN00048       2         0  Meal Plan 2        0         0
48  GI00049   INN00049       2         0  Meal Plan 1        0         1